# Generated by Django 4.1.7 on 2023-03-19 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=100)),
                ('creditos', models.IntegerField()),
                ('descrip_curso', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso_Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=5)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursoapp.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_profesor', models.CharField(max_length=200)),
                ('apellido_profesor', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tarea', models.CharField(max_length=200)),
                ('descrip_tarea', models.TextField()),
                ('curso_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursoapp.curso_profesor')),
            ],
        ),
        migrations.AddField(
            model_name='curso_profesor',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursoapp.profesor'),
        ),
    ]
